// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qgzdikcdsaklyndeigra.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFnemRpa2Nkc2FrbHluZGVpZ3JhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxNDc0NDYsImV4cCI6MjA3NzcyMzQ0Nn0.Z81H8u4RXo0OOxJaXQ2s_u56q6qjfB-bIB_YVt3XVHA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});